### ISSUE TITLE
./build.sh: Failed to pull chrome.manifest. Giving up.

### ISSUE THREAD

**Issue by Bahanix** [mozilla-b2g/device-flame#86]
Well, I am really unsure where to open an issue.

I followed https://github.com/mozilla-b2g/B2G steps to flash my flame. When I `./build.sh`, I get this error:

    Pulling "chrome.manifest"
    cp: cannot stat '../../../backup-flame/system/b2g/distribution/bundles/b2g_time/chrome.manifest': No such file or directory
    Failed to pull chrome.manifest. Giving up.

I absolutely do not know what is this file, but when I read `B2G_TIME_BUNDLE` [here](https://github.com/mozilla-b2g/device-flame/blob/master/extract-files.sh#L243), it reminds me that everytime I reboot my Flame, I have to set again datetime.

At the moment, my Flame is locked in the "ThunderSoft" splashscreen and I am unable to do anything.

**Comment by michaelwu** [comment]
See https://developer.mozilla.org/en-US/Firefox_OS/Phone_guide/Flame/Updating_your_Flame to update your device, delete backup-flame, and try again. More Flame specific documentation is available there.
